os:
  - linux
  - osx
  - windows

language: c

python:
  - "2.7"

notifications:
  email: false

git:
  depth: 10

dist: xenial

matrix:
  include:
    - os: linux
      env: ARCH_OPTION=""
      compiler: gcc
    - os: osx
      env: ARCH_OPTION=""
      compiler: gcc
    - os: windows
      env: ARCH_OPTION="-A x64"

install:
  - pip install --user -r requirements.txt

before_script:
  - mkdir build && cd build && cmake .. $ARCH_OPTION

script:
  # Compile, link, install.
  - cmake --build . --target install --config Release
  # Test and clean.
  - ctest -C Release && python ../tests/test_summary.py ../tests
  # Compare.
  - git status tests
  - git diff --exit-code tests
