os:
  - linux
  - osx
  - windows

language: C

python:
  - "2.7"

notifications:
  email: false

git:
  depth: 10

compiler:
  - gcc

# Execute tests
script:
  - make build
  - make test
  - git status tests
  - git diff --exit-code tests
