os:
  - linux
  - osx

language: C

python:
  - "2.7"

notifications:
  email: false

git:
  depth: 10

dist: xenial

compiler:
  - gcc

install:
  - pip install --user -r requirements.txt

before_script:
  - mkdir build && cd build && cmake ..

script:
  # Compile, link, install.
  - cmake --build . --target install
  # Test and clean.
  - ctest -E plot && python ../tests/test_summary.py ../tests -B
  # Compare.
  - git status tests
  - git diff --exit-code tests
