dist: trusty

sudo: true

language: C

python:
  - "2.7"

notifications:
  email: false

git:
  depth: 10

compiler:
  - gcc

before_script:
   export PYTHONPATH=$PYTHONPATH:$(pwd)/bin

# Execute tests
script:
  - make build
  - make test
  - git status tests
  - git diff --exit-code tests
